FROM python:3.9-alpine

WORKDIR /code/app

COPY ./requirements.txt /code/requirements.txt

RUN apk update && \
    apk add --no-cache gcc musl-dev libffi-dev openssl-dev && \
    pip install --upgrade pip && \
    pip install --no-cache-dir --upgrade -r /code/requirements.txt && \
    apk del gcc musl-dev libffi-dev openssl-dev

COPY ./ /code/app

ENTRYPOINT ["python", "milibre.py"]